name: Build on Linux

on: [push, workflow_dispatch]

jobs:
  build-linux-jammy:
    uses: ./.github/workflows/common-flow-host.yml
    with:
      env: ubuntu-22.04
      get-redis: true
    secrets: inherit
