name: Build on Linux Platforms

on:
  workflow_dispatch:
    inputs:
      platforms:
        type: choice
        options:
          - ubuntu:jammy
          - ubuntu:bionic
          - centos:7
          - rockylinux:8
          - debian:bullseye
        description: 'Build platforms'
        default: 'all'

jobs:
  build-linux-matrix:
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms.options) }}
      fail-fast: false
    uses: ./.github/workflows/common-flow.yml
    with:
      get-redis: true
      container: ${{ matrix.OS }}
    secrets: inherit
