name: Build on Linux Platforms

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        default: '["ubuntu:jammy", "ubuntu:bionic", "centos:7", "rockylinux:8", "debian:bullseye"]'

jobs:
  build-linux-matrix:
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms) }}
      fail-fast: false
    uses: ./.github/workflows/common-flow.yml
    with:
      get-redis: true
      env: ubuntu-latest
      container: ${{ matrix.OS }}
      container_options: --cpus 2
    secrets: inherit
