name: Build on Linux Platforms

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        default: '["ubuntu:jammy", "ubuntu:bionic", "centos:7", "rockylinux:8", "debian:bullseye"]'

jobs:
  build-linux-matrix:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    strategy:
      matrix:
        OS: ${{ fromJson(inputs.platforms) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        set-safe-directory: '*'
    # - run: |
    #     git config --global --add safe.directory '*'
    #     git submodule update --init --recursive
    - name: Setup
      run: |
        ./sbin/setup
        export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        ./deps/readies/bin/getredis --with-github-token
    - name: Test flow
      uses: ./.github/actions/common-flow.yml
