name: Build on Linux Platforms

on:
  workflow_dispatch:
    inputs:
      platforms:
        type: choice
        options:
          - all
          - ubuntu:jammy
          - ubuntu:bionic
          - centos:7
          - rockylinux:8
          - debian:bullseye
        description: 'Build platforms'
        default: 'all'

jobs:
  get-required-envs:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.get_platforms.outputs.platforms }}
    steps:
      - name: Get platforms
        id: get_platforms
        shell: python
        run: |
          import os
          if '${{inputs.platforms}}' == 'all':
            platforms = list(${{toJson(fromJson(inputs.platforms.options))}})
          else:
            platforms = [${{inputs.platforms}}]
          with os.fdopen(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f'platforms={platforms}'
  build-linux-matrix:
    needs: get-required-envs
    strategy:
      matrix:
        OS: ${{ fromJson(needs.get-required-envs.outputs.platforms) }}
      fail-fast: false
    uses: ./.github/workflows/common-flow-container.yml
    with:
      get-redis: true
      container: ${{ matrix.OS }}
    secrets: inherit
