name: default (common) flow

on:
  workflow_call:
    inputs:
      san: # name of the flow to run
        type: string
      get-redis:
        type: boolean
      env:
        required: true
        type: string

jobs:
  commom-flow:
    runs-on: "${{ inputs.env }}"
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          set-safe-directory: "'*'"
      - name: Setup
        run: |
          ./sbin/setup
          if [ "${{ inputs.get-redis }}" = "true" ]; then
            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            ./deps/readies/bin/getredis --with-github-token
          fi
      - name: Build
        run: |
          make SAN=${{ inputs.san }}
          make COORD=1 SAN=${{ inputs.san }}
      - name: Unit tests
        run: |
          make unit-tests SAN=${{ inputs.san }}
      - name: Flow tests
        run: |
          make pytest QUICK=1 SAN=${{ inputs.san }}
      - name: Unit tests (coordinator)
        run: |
          make COORD=1 unit-tests SAN=${{ inputs.san }}
      - name: Flow tests (coordinator)
        run: |
          make COORD=1 pytest QUICK=1 SAN=${{ inputs.san }}
