name: default (common) flow

on:
  workflow_call:
    inputs:
      env:
        default: "ubuntu-latest"
        type: string
      san:
        type: string
      get-redis:
        type: boolean
      container:
        type: string
      container_options:
        type: string

# Cannot unify the two flows because of the container job definition
# Make sure to keep them in sync
jobs:
  common-container-flow:
    runs-on: ${{ inputs.env }}
    container:
      image: ${{ inputs.container }}
      options: ${{ inputs.container_options }}
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Repo
        run: |
          git config --global --add safe.directory '*'
          git submodule update --init --recursive
      - name: Setup
        run: |
          ./sbin/setup
      - name: Get Redis
        if: ${{ inputs.get-redis }}
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ./deps/readies/bin/getredis --with-github-token
      - name: Build
        run: |
          make SAN=${{ inputs.san }}
          make COORD=1 SAN=${{ inputs.san }}
      - name: Unit tests
        run: |
          make unit-tests SAN=${{ inputs.san }}
      - name: Flow tests
        run: |
          make pytest QUICK=1 SAN=${{ inputs.san }}
      - name: Unit tests (coordinator)
        run: |
          make COORD=1 unit-tests SAN=${{ inputs.san }}
      - name: Flow tests (coordinator)
        run: |
          make COORD=1 pytest QUICK=1 SAN=${{ inputs.san }}
