name: default (common) flow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      san: # name of the flow to run
        type: string
      get-redis:
        type: boolean
      container:
        type: string
        default: null
      container_options:
        type: string
        default: null

jobs:
  commom-flow:
    runs-on: "${{ inputs.env }}"
    container:
      image: ${{ inputs.container }}
      options: ${{ inputs.container_options }}
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          ./sbin/setup
      - name: Setup Repo
        run: |
          git config --global --add safe.directory '*'
          git submodule update --init --recursive
      - name: Get Redis
        if: ${{ inputs.get-redis }}
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          ./deps/readies/bin/getredis --with-github-token
      - name: Build
        run: |
          make SAN=${{ inputs.san }}
          make COORD=1 SAN=${{ inputs.san }}
      - name: Unit tests
        run: |
          make unit-tests SAN=${{ inputs.san }}
      - name: Flow tests
        run: |
          make pytest QUICK=1 SAN=${{ inputs.san }}
      - name: Unit tests (coordinator)
        run: |
          make COORD=1 unit-tests SAN=${{ inputs.san }}
      - name: Flow tests (coordinator)
        run: |
          make COORD=1 pytest QUICK=1 SAN=${{ inputs.san }}
