name: default (common) flow

on:
  workflow_call:
    inputs:
      san: # name of the flow to run
        type: string

jobs:
  flow:
    runs-on: inehrited from caller workflow
    steps:
    - name: Build
      run: |
        make SAN=${{ github.event.inputs.san }}
        make COORD=1 SAN=${{ github.event.inputs.san }}
    - name: Unit tests
      run: |
        make unit-tests SAN=${{ github.event.inputs.san }}
    - name: Flow tests
      run: |
        make pytest QUICK=1 SAN=${{ github.event.inputs.san }}
    - name: Unit tests (coordinator)
      run: |
        make COORD=1 unit-tests SAN=${{ github.event.inputs.san }}
    - name: Flow tests (coordinator)
      run: |
        make COORD=1 pytest QUICK=1 SAN=${{ github.event.inputs.san }}
