name: CLang Sanitizer

on: [push, workflow_dispatch]

jobs:
  clang-sanitizer:
    uses: ./.github/workflows/common-flow-container.yml
    with:
      container: redisfab/clang:16-x64-bullseye
      san: addr
    secrets: inherit
