name: CLang Sanitizer

on:
  push:
  workflow_dispatch:

jobs:
  clang-sanitizer:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    container:
      image: redisfab/clang:16-x64-bullseye
      options: --cpus 2
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        set-safe-directory: '*'
    # - run: |
    #     git config --global --add safe.directory '*'
    #     git submodule update --init --recursive
    - name: Setup
      run: |
        ./sbin/setup
    - name: Test flow
      uses: ./.github/actions/common-flow.yml
      with:
        san: addr
